DROP TABLE COFFEE IF EXISTS;

CREATE TABLE PUBLIC.COFFEE (
	COFFEE_ID BIGINT NOT NULL AUTO_INCREMENT,
	BRAND CHARACTER VARYING(20),
	ORIGIN CHARACTER VARYING(20),
	"CHARACTERISTICS" CHARACTER VARYING(30),
	CONSTRAINT COFFEE_PK PRIMARY KEY (COFFEE_ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_99 ON PUBLIC.COFFEE (COFFEE_ID);